config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'users#welcome'

  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  resources :users, only: [:new, :create, :show, :edit, :update]
  get '/find_a_friend', to: 'users#find_a_friend', as: :find_a_friend
  get 'leave_friendship', to: 'users#end_friendship', as: :end_friendship
  
  resources :activities, only: [:index]
  get '/activities', to: 'activities#index', as: :adventures

  resources :buddies, only: [:show, :index]

  get 'lift_weights', to: 'hangouts#lift_weights'
  get 'go_run', to: 'hangouts#go_run'
  get 'yoga', to: 'hangouts#yoga'
  get 'abercrombie', to: 'hangouts#abercrombie'
  get 'hot_topic', to: 'hangouts#hot_topic'
  get 'h_and_m', to: 'hangouts#h_and_m'
  get 'cafe', to: 'hangouts#cafe'
  get 'pizza', to: 'hangouts#pizza'
  get 'mexican', to: 'hangouts#mexican'

end

app/models/activity.rb
class Activity < ApplicationRecord
    has_many :hangouts 
    has_many :friendships, through: :hangouts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buddy.rb
class Buddy < ApplicationRecord
    has_many :friendships


    
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :user
    belongs_to :buddy 
    has_many :hangouts 
    has_many :activities, :through => :hangouts


end

app/models/hangout.rb
class Hangout < ApplicationRecord
    belongs_to :friendship
    belongs_to :activity 
end

app/models/user.rb
class User < ApplicationRecord
    has_many :friendships
    validates :password, confirmation: { case_sensitive: true }
    validates :email, uniqueness: true
    validates :user_name, uniqueness: true
    validates :email, presence: true
    validates :password, presence: true
    validates :password_confirmation, presence: true

    
    has_secure_password 

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

    def index
        @activities = Activity.all
        render :index 
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception
helper_method :logged_in?
before_action :authenticate

  def current_user
    @user = User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def authenticate
    if logged_in?
      current_user
    else
      flash[:error] = "Wooooaaahh, slow down there, kiddo! You gotta log in to see that page!"
      redirect_to login_path
    end
  end

end

app/controllers/buddies_controller.rb
class BuddiesController < ApplicationController
  

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    
    
end

app/controllers/hangouts_controller.rb
class HangoutsController < ApplicationController

    # start_hangout creates an instance of a hangout using the activity id of that activity, 
    # and the friendship id of the current user, using the session's user_id
    # each activity will hold a unique numeric value
    # it will then call start_hangout, and use it to access the friendship to find the buddy's prefernces and compare it with it's numeric value. 
    # lastly, it will increment or decrement the friendship rank based on those results.
    # ENCAPSULATE

    

    def find_activity_id(pref_value)
       @activity = Activity.all.find_by(pref_value: pref_value)
       @activity.id
    end

    def find_friendship
        @user = User.find_by(id: session[:user_id])
        @friendship = Friendship.all.find_by(user_id: @user.id) # can probably just call session[:user_id] here instead of creating @user
    end

    def create_hangout(activity_id)
        @hangout = Hangout.create(activity_id: activity_id, friendship_id: @friendship.id)
    end

    def is_pref?(pref_value)
        if (0..2).include?(pref_value)
            @friendship.buddy.w_prefs == pref_value.to_s
        elsif (3..5).include?(pref_value)
            @friendship.buddy.s_prefs == pref_value.to_s
        elsif (6..8).include?(pref_value)
            @friendship.buddy.f_prefs == pref_value.to_s
        end
    end

    def adjust_rank(result)
        new_rank = result == true ? @friendship.friendship_rank += 1 : @friendship.friendship_rank -= 1
        @friendship.update(friendship_rank: new_rank)
    end

    def log_adventure(pref_value)
        new_adventures = @friendship.adventures += pref_value.to_s
        @friendship.update(adventures: new_adventures)
    end

    def win_lose_check
        if @friendship.friendship_rank <= 0
            redirect_to end_friendship_path
        else
            redirect_to user_path(@user)
        end
    end

    def adventure_available?(pref_value)
        !@friendship.adventures.include?(pref_value.to_s)
    end

    def find_and_compare(pref_value) # also since all these methods will be encapsulated, probably don't need to pass in these values beyond the first pref_value
        find_friendship 
        if adventure_available?(pref_value)
            activity_id = find_activity_id(pref_value)
            create_hangout(activity_id)
            result = is_pref?(pref_value)
            adjust_rank(result)
            log_adventure(pref_value)
            win_lose_check
        else
            redirect_to activities_path
        end
        
    end

    def lift_weights
        find_and_compare(0)
    end

    def go_run
        find_and_compare(1)
    end

    def yoga
        find_and_compare(2)
    end

    def abercrombie
        find_and_compare(3)
    end

    def hot_topic
        find_and_compare(4)
    end

    def h_and_m
        find_and_compare(5)
    end

    def cafe
        find_and_compare(6) 
   end

    def pizza
        find_and_compare(7)
    end

    def mexican
        find_and_compare(8)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :authenticate, only: [:new, :create, :destroy]

    def new
      render :new
    end
  
    def create
      @user = User.find_by(email: params[:user]['email'])
        
  
      if @user && @user.authenticate(params[:user]['password'])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        flash[:error] = "Sorry, bud! That login was invalid"
        redirect_to login_path
      end
    end
  
    def destroy
      session.delete(:user_id) 
      redirect_to '/'
    end

    private

    def user_params
        params.require(:user).permit(:id, :user_name, :password, :password_confirmation, :email, :name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authenticate, only: [:welcome, :new, :create]
    helper_method :has_friendship?, :current_buddy
    def welcome
        #implicitly renders welcome
    end
    
    def show
        @user = User.find_by(id: params[:id])||@user = User.find_by(id: session[:user_id])
    end

    def create
        @user = User.new(user_params)
        if @user.valid?
            @user.save
            redirect_to login_path
        else
            render :new
        end
    end

    def new
        render :new
    end

    def has_friendship?
        Friendship.all.find_by(user_id: @user.id)
    end

    def current_buddy
        @buddy = Buddy.all.find_by(id: @user.friendships.first.buddy_id)
    end

    def find_a_friend
        @buddy = Buddy.all.sample 
        Friendship.create(user_id: @user.id, buddy_id: @buddy.id, friendship_rank: 3, adventures: "")
        render :show
    end
    
    def end_friendship
        Friendship.all.find_by(user_id: @user.id).destroy
        render :show
    end

    private
    def user_params
        params.require(:user).permit(:user_name, :password, :password_confirmation, :email, :name)
    end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buddies_helper.rb
module BuddiesHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/hangouts_helper.rb
module HangoutsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/index.html.erb
<!-- Seed the sub activities, not the categories. Display pictures of activity categories, with usable activities 
underneath in a dropdown or collection_select. Seed activities: Active:--Go to the gym, Go dancing, Go on a hike-- 
Shopping:--Abercrombie, Hot Topic, H&M--  Conversation: --coffee, take a walk, food/bar--  
Entertainment:-- video games, see a movie, see a concert-- 
organizing the collection select: In the schema we have activity names and activity types. We can add an activity "value" 
to correspond with friend preferences. activity type can be the activity category, and name can be specific -->
<!-- <#%= f.collection_select(:power_id, Power.all, :id, :name) %><br> -->

<section class="mbr-section mbr-section-hero mbr-section-full" id="adventure-show-page">
        <div class="adventure-container">
            <div class="adventure-content">
                <div class="ad-1">
                        <h1>Workout</h1><br> 
                    <div class="workout-photo">
                        <%= image_tag ("/assets/activity_imgs/workingout.png"), class: "mbr-figure"%>
                    </div> 
                    <div class="activity-buttons">
                        <p><br><%= link_to 'Yoga', yoga_path, :class => "btn btn-black" %><br></p>
                        <p><%= link_to 'Weight Lifting', lift_weights_path, :class => "btn btn-black" %><br></p>
                        <p><%= link_to 'Running', go_run_path, :class => "btn btn-black" %></p>
                    </div>
                </div>
                <div class="ad-2">
                    <h1>Shopping</h1>
                    <div class="shopping-photo">
                            <%= image_tag ("/assets/activity_imgs/shopping.png"), class: "mbr-figure"%>
                    </div> 
                    <div class="activity-buttons">
                            <p><br><%= link_to 'Abercrombie', abercrombie_path, :class => "btn btn-black" %><br></p>
                            <p><%= link_to 'H&M', h_and_m_path, :class => "btn btn-black" %><br></p>
                            <p><%= link_to 'Hot Topic', hot_topic_path, :class => "btn btn-black" %></p>
                        </div>
                </div>
                <div class="ad-3">
                    <h1>Food</h1>
                    <div class="food-photo">
                            <%= image_tag ("/assets/activity_imgs/eating.png"), class: "mbr-figure"%>
                    </div> 
                    <div class="activity-buttons">
                            <p><br><%= link_to 'Cafe', cafe_path, :class => "btn btn-black" %><br></p>
                            <p><%= link_to 'Pizza', pizza_path, :class => "btn btn-black" %><br></p>
                            <p> <%= link_to 'Mexican', mexican_path, :class => "btn btn-black" %></p>
                        </div>
                </div>
            </div>
        </div>
    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic&amp;subset=latin">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="https://mobirise.com/free-template/app-showcase-demo/assets/bootstrap-material-design-font/css/material.css">
    <link rel="stylesheet" href="https://mobirise.com/free-template/app-showcase-demo/assets/web/assets/mobirise-icons/mobirise-icons.css">
    <link rel="stylesheet" href="https://mobirise.com/free-template/app-showcase-demo/assets/et-line-font-plugin/style.css">
    <link rel="stylesheet" href="https://mobirise.com/free-template/app-showcase-demo/assets/tether/tether.min.css">
    <link rel="stylesheet" href="https://mobirise.com/free-template/app-showcase-demo/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://mobirise.com/free-template/app-showcase-demo/assets/dropdown/css/style.css">
    <link rel="stylesheet" href="https://mobirise.com/free-template/app-showcase-demo/assets/animate.css/animate.min.css">
    <link rel="stylesheet" href="https://mobirise.com/free-template/app-showcase-demo/assets/theme/css/style.css">
    <link rel="stylesheet" href="https://mobirise.com/free-template/app-showcase-demo/assets/mobirise/css/mbr-additional.css" type="text/css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>

    <script src="https://mobirise.com/free-template/app-showcase-demo/assets/web/assets/jquery/jquery.min.js"></script>
    <script src="https://mobirise.com/free-template/app-showcase-demo/assets/tether/tether.min.js"></script>
    <script src="https://mobirise.com/free-template/app-showcase-demo/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://mobirise.com/free-template/app-showcase-demo/assets/smooth-scroll/smooth-scroll.js"></script>
    <script src="https://mobirise.com/free-template/app-showcase-demo/assets/dropdown/js/script.min.js"></script>
    <script src="https://mobirise.com/free-template/app-showcase-demo/assets/touch-swipe/jquery.touch-swipe.min.js"></script>
    <script src="https://mobirise.com/free-template/app-showcase-demo/assets/viewport-checker/jquery.viewportchecker.js"></script>
    <script src="https://mobirise.com/free-template/app-showcase-demo/assets/jarallax/jarallax.js"></script>
    <script src="https://mobirise.com/free-template/app-showcase-demo/assets/theme/js/script.js"></script>

    <input name="animation" type="hidden">
    
  </body>
</html>

app/views/users/new.html.erb
<section class="mbr-section mbr-section-hero mbr-section-full" id="create-page">
        <div class="create-container">
            <div>
            <% if@user %>
                <% if @user.errors.any? %>
                <div id="error_explanation">
                <h4>Whoops! Looks like something you entered wasn't quite right...</h4>
                 <ul>
                    <% @user.errors.full_messages.each do |msg| %>
                     <li><%= msg %></li>
                    <% end %>
                 </ul>
                </div>
                <% end %>
                <% end %>
            
                <%= form_for :user, method: 'post', url: '/users' do |f| %>
                <b>Name <br><%= f.text_field :name %><br><br>  
                Username <br><%= f.text_field :user_name %><br><br>  
                Email <br> <%= f.text_field :email %><br><br>  
                Password<br><%= f.password_field :password %><br><br>  
                Password Confirmation <br><%= f.password_field :password_confirmation %><br><br>  
                <%= f.submit "Create that account, champ!", :class => "btn btn-black" %>
                <% end %></b>
            </div>
        </div>
    </section>

app/views/users/show.html.erb
<link href="https://fonts.googleapis.com/css?family=Titan+One&display=swap" rel="stylesheet">
<section class="mbr-section mbr-section-hero mbr-section-full" id="user-show-page">
    <div class="profile-container">
        <div class="profile-content-user">
            <div class="item-1">
                <div class="monster-content">
                    <%= image_tag ("/assets/cookie.png"), class: "mbr-figure"%>
                </div>
                 <div class="monster-button">
                    <%= link_to 'LOGOUT', logout_path, :class => "btn btn-black" %>
                </div>
            </div>
            <div class="item-2">
                <div class="item-2-content">
                    <h1>Welcome <%= @user.name %>!</h1><br> 
                    <h2>Username: <%= @user.user_name %><br>
                    <br>Email: <%= @user.email %><br>
                    <% if has_friendship? %>
                    <br><% @buddy = current_buddy %>
                    <br>Your Friend: <br>
                    <div id="name-font">
                        <br><%= @buddy.name %>  
                    </div>
                    <br>Friend Rank: <%= Friendship.all.find_by(user_id: @user.id).friendship_rank %> <br>
                    <% end %></h2>
                </div>
            </div>
            <div class="item-3">
                <!-- if user has friendship, display friend image and adventure button, else display find friend button -->
                <% if has_friendship? %>
                    <% @buddy = current_buddy %>
                    <div class="friend-picture">
                        <%= image_tag ("/assets/buddies_imgs/#{@buddy.img_num}.png"), class: "mbr-figure"%>                
                    </div>

                    <div class="friend-buttons">
                        <%= link_to 'GO ON AN ADVENTURE!', activities_path, :class => "btn btn-black" %><br><br> 
                        <br><%= link_to 'LEAVE YOUR FRIEND 😥', end_friendship_path, :class => "btn btn-black" %>
                        <%else%>
                        <%= link_to 'FIND A FRIEND', find_a_friend_path, :class => "btn btn-black" %>
                <%end%>
                    </div>
            </div>
        </div>
    </div>
</section>







        <!-- <div class="profile-content-friend">
            <h1>Hello</h1>
        </div> -->
<!-- 
    <div class="menu-container">
        <div class="user-menu-option-1">
            <h1>OPTION 1</h1>
        </div>
        <div class="user-menu-option-2">
            <h1>OPTION 2</h1>
        </div>
        <div class="user-menu-option-3">
            <h1>OPTION 3</h1>
        </div>
    </div> -->

app/views/users/welcome.html.erb
<link href="https://fonts.googleapis.com/css?family=Caveat&display=swap" rel="stylesheet">
</section><section class="engine"><a rel="external" href="https://mobirise.com">Mobirise</a></section></div>

<section class="mbr-section mbr-section-hero mbr-section-full header2 mbr-parallax-background mbr-after-navbar" id="header2-1" style="background-image: url(https://i.pinimg.com/originals/ec/31/13/ec31133896846936d4f2f3b52b987161.jpg);">

    <div class="mbr-overlay" style="opacity: 0.3; background-color: rgb(71, 85, 119);">
    </div>

    <div class="mbr-table mbr-table-full">
        <div class="mbr-table-cell">

            <div class="container">
                <div class="mbr-section row">
                    <div class="mbr-table-md-up">

                        <div class="mbr-table-cell col-md-5 text-xs-center text-md-right ">

                            <h3 class="mbr-section-title display-2">IMAGINE</h3>

                            <div class="mbr-section-text">
                                <p>"Stranger just friend me have not shared cookie with yet."&nbsp;</p>
                            </div>

                            <div class="mbr-section-btn">
                                <%= link_to 'LOGIN', '/login', :class => "btn btn-black" %>
                                <%= link_to 'CREATE ACCOUNT', new_user_path, :class => "btn btn-black" %>
                            </div>

                        </div>
                        <div class="mbr-table-cell mbr-valign-top mbr-left-padding-md-up col-md-7 image-size" style="width: 50%;">
                            <div class="cookie-monster-float">
                                <%= image_tag ("/assets/cookie.png"), class: "mbr-figure"%>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>    

</section>
        